package com.jeecloud.common.entity.system;

import java.io.Serializable;
import java.util.Date;

/**
 * 
 * @ClassName: CompanyMenu 
 * @Description: 企业菜单
 * @author: admin
 * @date: 2018年3月6日 上午11:47:04
 */
public class CompanyMenu implements Serializable{
    /**
	 * @fieldName: serialVersionUID
	 * @fieldType: long
	 * @Description: TODO
	 */
	private static final long serialVersionUID = 1L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_menu.id
     *
     * @mbg.generated Tue Mar 06 11:46:29 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_menu.company_id
     *
     * @mbg.generated Tue Mar 06 11:46:29 CST 2018
     */
    private Long companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_menu.parent_id
     *
     * @mbg.generated Tue Mar 06 11:46:29 CST 2018
     */
    private Long parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_menu.name
     *
     * @mbg.generated Tue Mar 06 11:46:29 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_menu.url
     *
     * @mbg.generated Tue Mar 06 11:46:29 CST 2018
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_menu.perms
     *
     * @mbg.generated Tue Mar 06 11:46:29 CST 2018
     */
    private String perms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_menu.type
     *
     * @mbg.generated Tue Mar 06 11:46:29 CST 2018
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_menu.icon
     *
     * @mbg.generated Tue Mar 06 11:46:29 CST 2018
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_menu.sort
     *
     * @mbg.generated Tue Mar 06 11:46:29 CST 2018
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_menu.is_deleted
     *
     * @mbg.generated Tue Mar 06 11:46:29 CST 2018
     */
    private int isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_menu.gmt_create
     *
     * @mbg.generated Tue Mar 06 11:46:29 CST 2018
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_menu.gmt_creater
     *
     * @mbg.generated Tue Mar 06 11:46:29 CST 2018
     */
    private String gmtCreater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_menu.gmt_modified
     *
     * @mbg.generated Tue Mar 06 11:46:29 CST 2018
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_menu.gmt_reviser
     *
     * @mbg.generated Tue Mar 06 11:46:29 CST 2018
     */
    private String gmtReviser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_menu.id
     *
     * @return the value of company_menu.id
     *
     * @mbg.generated Tue Mar 06 11:46:29 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_menu.id
     *
     * @param id the value for company_menu.id
     *
     * @mbg.generated Tue Mar 06 11:46:29 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_menu.company_id
     *
     * @return the value of company_menu.company_id
     *
     * @mbg.generated Tue Mar 06 11:46:29 CST 2018
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_menu.company_id
     *
     * @param companyId the value for company_menu.company_id
     *
     * @mbg.generated Tue Mar 06 11:46:29 CST 2018
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_menu.parent_id
     *
     * @return the value of company_menu.parent_id
     *
     * @mbg.generated Tue Mar 06 11:46:29 CST 2018
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_menu.parent_id
     *
     * @param parentId the value for company_menu.parent_id
     *
     * @mbg.generated Tue Mar 06 11:46:29 CST 2018
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_menu.name
     *
     * @return the value of company_menu.name
     *
     * @mbg.generated Tue Mar 06 11:46:29 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_menu.name
     *
     * @param name the value for company_menu.name
     *
     * @mbg.generated Tue Mar 06 11:46:29 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_menu.url
     *
     * @return the value of company_menu.url
     *
     * @mbg.generated Tue Mar 06 11:46:29 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_menu.url
     *
     * @param url the value for company_menu.url
     *
     * @mbg.generated Tue Mar 06 11:46:29 CST 2018
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_menu.perms
     *
     * @return the value of company_menu.perms
     *
     * @mbg.generated Tue Mar 06 11:46:29 CST 2018
     */
    public String getPerms() {
        return perms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_menu.perms
     *
     * @param perms the value for company_menu.perms
     *
     * @mbg.generated Tue Mar 06 11:46:29 CST 2018
     */
    public void setPerms(String perms) {
        this.perms = perms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_menu.type
     *
     * @return the value of company_menu.type
     *
     * @mbg.generated Tue Mar 06 11:46:29 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_menu.type
     *
     * @param type the value for company_menu.type
     *
     * @mbg.generated Tue Mar 06 11:46:29 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_menu.icon
     *
     * @return the value of company_menu.icon
     *
     * @mbg.generated Tue Mar 06 11:46:29 CST 2018
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_menu.icon
     *
     * @param icon the value for company_menu.icon
     *
     * @mbg.generated Tue Mar 06 11:46:29 CST 2018
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_menu.sort
     *
     * @return the value of company_menu.sort
     *
     * @mbg.generated Tue Mar 06 11:46:29 CST 2018
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_menu.sort
     *
     * @param sort the value for company_menu.sort
     *
     * @mbg.generated Tue Mar 06 11:46:29 CST 2018
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_menu.is_deleted
     *
     * @return the value of company_menu.is_deleted
     *
     * @mbg.generated Tue Mar 06 11:46:29 CST 2018
     */
    public int getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_menu.is_deleted
     *
     * @param isDeleted the value for company_menu.is_deleted
     *
     * @mbg.generated Tue Mar 06 11:46:29 CST 2018
     */
    public void setIsDeleted(int isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_menu.gmt_create
     *
     * @return the value of company_menu.gmt_create
     *
     * @mbg.generated Tue Mar 06 11:46:29 CST 2018
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_menu.gmt_create
     *
     * @param gmtCreate the value for company_menu.gmt_create
     *
     * @mbg.generated Tue Mar 06 11:46:29 CST 2018
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_menu.gmt_creater
     *
     * @return the value of company_menu.gmt_creater
     *
     * @mbg.generated Tue Mar 06 11:46:29 CST 2018
     */
    public String getGmtCreater() {
        return gmtCreater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_menu.gmt_creater
     *
     * @param gmtCreater the value for company_menu.gmt_creater
     *
     * @mbg.generated Tue Mar 06 11:46:29 CST 2018
     */
    public void setGmtCreater(String gmtCreater) {
        this.gmtCreater = gmtCreater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_menu.gmt_modified
     *
     * @return the value of company_menu.gmt_modified
     *
     * @mbg.generated Tue Mar 06 11:46:29 CST 2018
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_menu.gmt_modified
     *
     * @param gmtModified the value for company_menu.gmt_modified
     *
     * @mbg.generated Tue Mar 06 11:46:29 CST 2018
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_menu.gmt_reviser
     *
     * @return the value of company_menu.gmt_reviser
     *
     * @mbg.generated Tue Mar 06 11:46:29 CST 2018
     */
    public String getGmtReviser() {
        return gmtReviser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_menu.gmt_reviser
     *
     * @param gmtReviser the value for company_menu.gmt_reviser
     *
     * @mbg.generated Tue Mar 06 11:46:29 CST 2018
     */
    public void setGmtReviser(String gmtReviser) {
        this.gmtReviser = gmtReviser;
    }
}