package com.jeecloud.common.entity.system;

import java.io.Serializable;
import java.util.Date;

/**
 * 
 * @ClassName: SysLog 
 * @Description: 系统日志实体类
 * @author: admin
 * @date: 2018年3月5日 下午3:10:05
 */
public class SysLog implements Serializable {
	private static final long serialVersionUID = 1L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * sys_log.id
	 * @mbg.generated Wed Feb 28 16:29:08 CST 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * sys_log.username
	 * @mbg.generated Wed Feb 28 16:29:08 CST 2018
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * sys_log.operation
	 * @mbg.generated Wed Feb 28 16:29:08 CST 2018
	 */
	private String operation;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * sys_log.method
	 * @mbg.generated Wed Feb 28 16:29:08 CST 2018
	 */
	private String method;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * sys_log.params
	 * @mbg.generated Wed Feb 28 16:29:08 CST 2018
	 */
	private String params;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * sys_log.time
	 * @mbg.generated Wed Feb 28 16:29:08 CST 2018
	 */
	private Long time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * sys_log.ip
	 * @mbg.generated Wed Feb 28 16:29:08 CST 2018
	 */
	private String ip;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * sys_log.gmt_create
	 * @mbg.generated Wed Feb 28 16:29:08 CST 2018
	 */
	private Date gmtCreate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database
	 * column sys_log.id
	 * @return the value of sys_log.id
	 * @mbg.generated Wed Feb 28 16:29:08 CST 2018
	 */
	public Long getId() {
		return id;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database
	 * column sys_log.id
	 * @param id the value for sys_log.id
	 * @mbg.generated Wed Feb 28 16:29:08 CST 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database
	 * column sys_log.username
	 * @return the value of sys_log.username
	 * @mbg.generated Wed Feb 28 16:29:08 CST 2018
	 */
	public String getUsername() {
		return username;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database
	 * column sys_log.username
	 * @param username the value for sys_log.username
	 * @mbg.generated Wed Feb 28 16:29:08 CST 2018
	 */
	public void setUsername(String username) {
		this.username = username;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database
	 * column sys_log.operation
	 * @return the value of sys_log.operation
	 * @mbg.generated Wed Feb 28 16:29:08 CST 2018
	 */
	public String getOperation() {
		return operation;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database
	 * column sys_log.operation
	 * @param operation the value for sys_log.operation
	 * @mbg.generated Wed Feb 28 16:29:08 CST 2018
	 */
	public void setOperation(String operation) {
		this.operation = operation;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database
	 * column sys_log.method
	 * @return the value of sys_log.method
	 * @mbg.generated Wed Feb 28 16:29:08 CST 2018
	 */
	public String getMethod() {
		return method;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database
	 * column sys_log.method
	 * @param method the value for sys_log.method
	 * @mbg.generated Wed Feb 28 16:29:08 CST 2018
	 */
	public void setMethod(String method) {
		this.method = method;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database
	 * column sys_log.params
	 * @return the value of sys_log.params
	 * @mbg.generated Wed Feb 28 16:29:08 CST 2018
	 */
	public String getParams() {
		return params;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database
	 * column sys_log.params
	 * @param params the value for sys_log.params
	 * @mbg.generated Wed Feb 28 16:29:08 CST 2018
	 */
	public void setParams(String params) {
		this.params = params;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database
	 * column sys_log.time
	 * @return the value of sys_log.time
	 * @mbg.generated Wed Feb 28 16:29:08 CST 2018
	 */
	public Long getTime() {
		return time;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database
	 * column sys_log.time
	 * @param time the value for sys_log.time
	 * @mbg.generated Wed Feb 28 16:29:08 CST 2018
	 */
	public void setTime(Long time) {
		this.time = time;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database
	 * column sys_log.ip
	 * @return the value of sys_log.ip
	 * @mbg.generated Wed Feb 28 16:29:08 CST 2018
	 */
	public String getIp() {
		return ip;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database
	 * column sys_log.ip
	 * @param ip the value for sys_log.ip
	 * @mbg.generated Wed Feb 28 16:29:08 CST 2018
	 */
	public void setIp(String ip) {
		this.ip = ip;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database
	 * column sys_log.gmt_create
	 * @return the value of sys_log.gmt_create
	 * @mbg.generated Wed Feb 28 16:29:08 CST 2018
	 */
	public Date getGmtCreate() {
		return gmtCreate;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database
	 * column sys_log.gmt_create
	 * @param gmtCreate the value for sys_log.gmt_create
	 * @mbg.generated Wed Feb 28 16:29:08 CST 2018
	 */
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}
}
